pair/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pair_pjt1.urls')),
]

pair_pjt1/urls.py
from django.urls import path
from . import views


app_name = "pair"

urlpatterns= [
    path("",views.index, name= "index"),
    path("create",views.create, name= "create"),
    path('send',views.send, name='send'),
    path('detail/<int:pk>',views.detail, name ='detail'),
    path('delete/<int:pk>',views.delete, name='delete'),
    path('edit/<int:pk>', views.edit, name="edit"),
    path('update/<int:pk>', views.update, name='update'),
    path('search/', views.search, name="search"),
]

pair_pjt1/models.py
from django.db import models


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True)
    update_ad = models.DateField(auto_now=True)

pair_pjt1/views.py
from datetime import date
from django.shortcuts import render, redirect
from .models import Review
from django.db.models import Q

# Create your views here.
def index(request):
    reviews = Review.objects.all().order_by("id")

    context = {
        "Review": reviews,
    }

    return render(request, "index.html", context)


def create(request):

    return render(request, "create.html")


def send(request):
    title = request.GET.get("title")
    content = request.GET.get("content")
    created_at = request.GET.get("created_at")
    update_ad = request.GET.get("update_ad")

    Review.objects.create(
        title=title,
        content=content,
        created_at=created_at,
        update_ad=update_ad,
    )

    return redirect("pair:index")


def detail(request, pk):
    pk = Review.objects.get(id=pk)

    context = {"id": pk}

    return render(request, "detail.html", context)


def delete(request, pk):
    pk = Review.objects.get(id=pk)
    pk.delete()

    return redirect("pair:index")


def edit(request, pk):
    pk = Review.objects.get(id=pk)

    context = {"pk": pk}

    return render(request, "edit.html", context)


def update(request, pk):
    pk = Review.objects.get(id=pk)

    title = request.GET.get("title")
    content = request.GET.get("content")

    pk.title = title
    pk.content = content

    pk.save()

    return redirect("pair:detail", pk.pk)


def search(request):
    content_list = Review.objects.all()  # 모든 데이데터베이스
    search = request.GET.get(
        "search", ""
    )  # search에 검색쿼리 정보 저장 검색창했을때 리퀘스트정보에서 서치정보가 없디면 "" 빈공간을 반환
    if (
        search
    ):  # seacrch가 True라면 서치리스트는 모든 데이터베이스 안에서 필터를 통해 걸른다 (타이틀에 search 변수의 인자가 있다면 반환)
        search_list = content_list.filter(Q(title__icontains=search))  #
    context = {
        "searched": search_list,
        "search": search,
    }  # 컨텍스트 변수에 딕트로 묶어서 전송

    return render(request, "search.html", context)

pair_pjt1/templates/create.html
{% extends 'base.html' %}

{% block content %}

<div class="container ">
    <div class="d-flex justify-content-center align-items-center" style="height: 10rem;">
        <h1 class="text-center">리뷰 글 작성</h1>
    </div>
    <hr>
    <div class="container d-flex justify-content-center ">
        <form action="{% url 'pair:send' %}">

            <div class="input-group input-group-lg mb-5" style="width: 50rem;">
                <span class="input-group-text" id="inputGroup-sizing-lg">제목</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                    aria-describedby="inputGroup-sizing-lg" name="title">
            </div>

            <div class="input-group input-group-lg mb-5" style="width: 50rem; height:20rem; ">
                <span class="input-group-text" id="inputGroup-sizing-lg">본문</span>
                <textarea type="text" class="form-control" aria-label="Sizing example input"
                    aria-describedby="inputGroup-sizing-lg" name="content"></textarea>
            </div>

            <div class="d-flex justify-content-center">
                <input class="btn btn-primary " type="submit" name="" id="" value="작성하기">
            </div>
        </form>
    </div>
</div>
{% endblock %}

pair_pjt1/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class=" d-flex justify-content-center align-items-center  " style="height: 10rem;">
    <h1 class="">리뷰 상세 보기</h1>

</div>
<div class="container">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">제목</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" value="{{ id.title }}" disabled readonly>
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">리뷰 내용</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" disabled
            readonly>{{ id.content }}</textarea>
    </div>
    <div class="d-flex justify-content-between">
        <a class="btn btn-primary" type="button" href="{% url 'pair:edit' id.pk %}">수정</a>
        <a class="btn btn-primary" type="button" href="{% url 'pair:delete' id.pk %}">삭제</a>
    </div>
</div>
{% endblock %}

pair_pjt1/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">
    <div class="d-flex justify-content-center align-items-center" style="height: 10rem;">
        <h1 class="text-center">리뷰 글 수정하기</h1>
    </div>
    <hr>
    <div class="container d-flex justify-content-center ">
        <form action="{% url 'pair:update' pk.pk %}">

            <div class="input-group input-group-lg mb-5" style="width: 50rem;">
                <span class="input-group-text" id="inputGroup-sizing-lg">제목</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                    aria-describedby="inputGroup-sizing-lg" name="title" value="{{pk.title}}">
            </div>

            <div class="input-group input-group-lg mb-5" style="width: 50rem; height:20rem; ">
                <span class="input-group-text" id="inputGroup-sizing-lg">본문</span>
                <textarea type="text" class="form-control" aria-label="Sizing example input"
                    aria-describedby="inputGroup-sizing-lg" name="content">{{pk.content}}</textarea>
            </div>

            <div class="d-flex justify-content-center">
                <input class="btn btn-primary " type="submit" name="" id="" value="작성하기">
            </div>
        </form>
    </div>
</div>


{% endblock %}

pair_pjt1/templates/index.html
{% extends 'base.html' %}


{% block content %}
<div>
    <div class=" d-flex justify-content-center align-items-center  " style="height: 10rem;">
        <h1 class="">리뷰 커뮤니티</h1>

    </div>
    <table class="table table-dark  table-hover p-3 container text-center">
        <thead>
            <th>리뷰 번호</th>
            <th>리뷰 제목</th>
            <th>작성 시간</th>

        </thead>

        <tbody>
            <tr>
                {%for k in Review%}
                <td>{{ k.id }} </td>
                <td><a href="{% url 'pair:detail' k.id %}">{{ k.title }}</a></td>
                <td>{{ k.created_at }}</td>
            </tr>
        </tbody>
        {% endfor %}

    </table>
    <div class="d-flex justify-content-end container">
        <a href="{% url 'pair:create' %}" class="btn btn-primary" role="button">리뷰 작성하기</a>
    </div>
</div>
{% endblock %}

pair_pjt1/templates/search.html
{% extends 'base.html' %}


{% block content %}
<div>
    <div class=" d-flex justify-content-center align-items-center  " style="height: 10rem;">
        <h1 class="">{{search}}에 대한 검색 결과</h1>

    </div>

    <table class="table table-dark  table-hover p-3 container text-center">
        <thead>
            <th>리뷰 번호</th>
            <th>리뷰 제목</th>
            <th>작성 시간</th>

        </thead>
        <tbody>
            <tr>
                {%for k in searched%}
                <td>{{ k.id }} </td>
                <td><a href="{% url 'pair:detail' k.id %}">{{ k.title }}</a></td>
                <td>{{ k.created_at }}</td>
            </tr>
        </tbody>
        {% endfor %}

    </table>
    <div class="d-flex justify-content-end container">
        <a href="{% url 'pair:create' %}" class="btn btn-primary" role="button">리뷰 작성하기</a>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body class="">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'pair:index' %}">HOME</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <form class="d-flex" role="search" Form method="GET" action="{% url 'pair:search' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <footer class="text-center p-3 mt-5 bg-dark text-white">하승찬 & 주세환 20220930</footer>
</body>

</html>